### ISSUE TITLE
Bring over #13 from legacy `sharkiq`

### ISSUE THREAD

**Issue by funkybunch** [JeffResc/sharkiq#1]
@Mobius5150 has a PR that adds room-level support on the legacy repo https://github.com/ajmarks/sharkiq/pull/13

This issue is being created to track migrating this PR over to the new repo.

**Comment by georgejung** [comment]
Would love this! Right now I can only do room cleaning via the shark app, and I can only do scheduling via HA. If we could get this merged it would be perfect! Thanks for your work on this

**Comment by georgejung** [comment]
Hi there, I see this has been completed, which is amazing! Thank you. Unfortunately I am not smart enough to figure out how to actually take advantage of the specific room cleaning within a Home Assistant automation. Any tips for the lay-folk out here? Or is this only 1 piece of the puzzle in order to have it working in HA? Cheers

**Comment by funkybunch** [comment]
@georgejung this is only half of the equation.  This is the dependency library upstream from Home Assistant core.  We have another PR on the Home Assistant repo where we now have to implement it into HA.  You can follow that update at https://github.com/home-assistant/core/pull/75676
