### ISSUE TITLE
Set default speed?

### ISSUE THREAD

**Issue by proactivematter** [JeffResc/sharkiq#38]
Hey, just wondering if there is a way to change the default speed? Tried a couple different ways but it always goes back to medium. I'm a pretty basic user when it comes to homeassistant, so I am sure I'm just missing something.

Many thanks and merry x-mas!

**Comment by funkybunch** [comment]
@proactivematter This is expected behavior.  Depending on the robot you have as they typically revert back to default settings after re-docking.  If you have automations setup in home assistant you can chance the speed before running.

Closing since this is not a bug or feature request.  If you'd like help on this please repost in the discussions section. Discussions is the correct place for implementation advice.

**Comment by proactivematter** [comment]
Alright. Sorry, I wasn't sure. Thanks.
