### ISSUE TITLE
Shark IQ unable to login to integration

### ISSUE THREAD

**Issue by scottWestveer** [JeffResc/sharkiq#50]
I thought it was because I changed the robot to a new IoT Wifi SSID.. it wasn't connecting to a pre-existing integration.. so i don't know how long the problem has existed.. but i deleted and tried to resetup the integration and it is failing to connect with username and password. Verified the credentials and can login direct to Shark App.

i checked the router and don't see anything blocking ads-field.aylanetworks.com

Log shows this interger error but i cant find any account number other than my email address..

Logger: homeassistant.components.sharkiq
Source: components/sharkiq/config_flow.py:59
integration: Shark IQ (documentation, issues)
First occurred: 2:14:08 PM (12 occurrences)
Last logged: 2:46:40 PM

string indices must be integers, not 'str'

Any help or guidance would be appreciated.

HA Yellow:
Core
2024.7.4
Supervisor
2024.08.0
Operating System
12.4
Frontend
20240710.0

**Comment by scottWestveer** [comment]
➜  ~ python3 --version
Python 3.12.3
➜  ~

**Comment by funkybunch** [comment]
Closing this issue as Home Assistant support is only available in the [Home Assistant Core repository](https://github.com/home-assistant/core/issues?q=is%3Aissue+label%3A%22integration%3A+sharkiq%22).  If you can't find the solution to your problem there, please open a new issue on the core repository following the Home Assistant Issue Template.

Be sure to include logs, otherwise we have no helpful information to go on.
